# fly.toml app configuration file generated for quotation-app-be
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "quotation-app-be"
primary_region = "sin"

[build]

[env]
  NODE_ENV = "production"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

[checks]
  [checks.health]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    path = "/health"
    port = 8000
    timeout = "5s"
    type = "http"
