[phases.setup]
nixPkgs = ['nodejs-18_x', 'npm-9_x']

[phases.install]
cmds = ['npm ci --only=production']

[phases.build]
cmds = ['echo "Build phase complete"']

[start]
cmd = 'node server.js'

[variables]
NODE_ENV = 'production'

# Health check configuration
[healthcheck]
path = '/health'
interval = 30
timeout = 10
retries = 3
start_period = 60
